export const texts = {
  id: 'ID',
  name: 'Name',
  status: 'Status',
  statusUpdateTime: 'Last Update Time',
  deviceGroup: 'Device Group',
  systemTags: 'System Tags',
  tags: 'Tags',
  connectionStatus: 'status',
  statusReason: 'Status Reason',
  statusReasonUpdateTime: 'Status Reason Update Time',
  createdAt: 'Created At',
  moduleId: 'Module ID',
  type: 'Type',
  edit: 'Edit',
  eventType: 'Event Type',
  eventTime: 'Event Time',
  eventMessage: 'Event Message',
  updating: 'Editing ...',
  create: 'Create',
  creating: 'Creating ...',
  critical: 'critical',
  delete: 'Delete',
  deleting: 'Deleting ...',
  cancel: 'Cancel',
  save: 'Save',
  saving: 'Saving ...',
  done: 'Done',
  connect: 'Connect',
  connecting: 'Connecting ...',
  disconnect: 'Disconnect',
  disconnecting: 'Disconnecting ...',
  subscribe: 'Subscribe',
  subscribed: 'Subscribed',
  subscribing: 'Subscribing ...',
  publish: 'Publish',
  publishing: 'Publishing ...',
  ok: 'OK',
  credentials: 'Credentials',
  reset: 'Reset',
  refetch: 'Refetch',
  setDefault: 'Set Default',
  formatJSON: 'Format JSON',
  discard: 'Discard',
  back: 'Back',
  retry: 'Retry',
  list: 'List',
  secondary: 'secondary',
  primary: 'primary',
  update: 'Update',
};
